### ISSUE TITLE
Offset for the left minimap

### ISSUE THREAD

**Issue by laughedelic** [olmokramer/atom-minimap-codeglance#10]
This is a nice plugin! I have one problem though.
When I set the minimap to be on the left side, codeglance covers it, which is quite inconvenient. Is it possible to move it relatively to the minimap?

**Comment by rugk** [comment]
~~Yes :+1: it would be great to not use the whole left side.~~

**Comment by rugk** [comment]
~Okay, I was able to do this by adding this to my stylesheet:

``` css
minimap-codeglance {
  width: 50%;
  margin-left: 50%;
}
```

Unfortunately in this mode it covers the minimap (which is a nice effect), but I think it would be nicer not to do so...

And if you like it this way you can do it like this:

``` css
minimap-codeglance {
  margin-left: 50%;
  margin-right: 10px;
}
```
