### ISSUE TITLE
Improvement: Make background-color translucent

### ISSUE THREAD

**Issue by markvandenbrink** [olmokramer/atom-minimap-codeglance#5]
I like your codeglance-plugin, but I think it is a good idea to make the background-color al little bit translucent so you can see the code behind it. I often find myself leaving the mouse cursor on the minimap while doing a quick code fix before I scroll to another point. Now the codeglance window is blocking the view and I have to move my mouse cursor out of the minimap. If the codeglance is somewhat translucent I can have best of both worlds :-)

Another consideration is adding a subtle shadow around the glance box to get a better distinction from the code window.

Thanks!

**Comment by olmokramer** [comment]
Hey Mark, thanks for your feedback! You can easily do these things from your own stylesheet. You can put this in your `~/.atom/styles.less`:

``` less
@import "syntax-variables";

atom-text-editor::shadow minimap-codeglance {
  background-color: fade(@syntax-background-color, 10%);
  box-shadow: 0 0 6px rgba(0, 0, 0, .5);
}
```

I deliberately didn't add a lot of styles, so that it's easy to overwrite the styles of the codeglance element. I do like the idea of a shadow, though, so I think I'll add that to the package.
Cheers, Olmo
