### ISSUE TITLE
customizing codeglance element styles not working

### ISSUE THREAD

**Issue by ghernandez345** [olmokramer/atom-minimap-codeglance#9]
I'm trying to customize the codeglance element but I cannot get it to work. I place my styles in ~/.atom/styles.less but none of them seem to have any effect. Here are the styles I've defined and the selector I am using.

``` less
atom-text-editor::shadow minimap-codeglance {
  // see-through but leaves text opaque
  background-color: fade(@syntax-background-color, 10%);
  // change the shadow of the element
  box-shadow: 0 0 10px rgba(255, 0, 0, .5);
  // etc.
}
```

I restart atom after making changes and still see no style changes. Also, styles for other selectors seem to work fine. Im using codeglace version 0.4.0 and atom version 1.0.5
